#!/bin/bash

## ssh config
if [[ ! -d ~/.ssh ]]; then
  mkdir -p ~/.ssh
fi
if [[ -f ~/.ssh/config ]]; then
  mv ~/.ssh/config ~/.ssh/config.orig
fi
cp ./ssh_config ~/.ssh/config

## zshrc
if [[ -f ~/.zshrc ]]; then
  mv ~/.zshrc ~/.zshrc.orig
fi
cp ./zshrc ~/.zshrc

## vimrc
if [[ -f ~/.vimrc ]]; then
  mv ~/.vimrc ~/.vimrc.orig
fi
cp ./vimrc ~/.vimrc

